default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWD'] %>

development:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME']}_development" %>

test:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME']}_test" %>

production:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME']}_prod" %>

